vm_types:
- name: default
  stemcell:
    os: ubuntu-trusty
    version: latest
  cloud_properties:
    ephemeral_disk:
      size: 1024
      type: gp2
disk_types:
- name: default
  disk_size: 1024
compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  vm_type: default
networks:
- name: default
  subnets:
  - reserved: [10.244.0.1]
    range: 10.244.0.0/24
    cloud_properties:
      name: random
